### ISSUE TITLE
Move to a GitHub organization?

### ISSUE THREAD

**Issue by jacebrowning** [doorstop-dev/doorstop#243]
How would people feel about moving Doorstop to its own GitHub organization? This would simplify collaborator management and open up the possibility of promoting other tools built on Doorstop (e.g. https://github.com/nickvanderstel/doorstop-qt cc @nickvanderstel).

**Comment by devcurmudgeon** [comment]
I think it's worth getting complementary projects to collaborate together so I think this is a sensible idea. 

I'd gently suggest that you might consider moving to gitlab, and establishing the organisation there (since gitlab is FOSS). 

Equally (at the risk of plugging a different project) 'd be excited to invite doorstop to become part of the 'trustable' organisation on gitlab , since I know that some members of that community are interested in requirements management - we can offer mailing list, irc etc if that's of interest.

But in any case, yes I think it makes sense to get doorstop into an organisation so if folks prefer a new GitHub org I'm +1

**Comment by michaelnt** [comment]
I don't imagine it would make much difference but I'm happy with things as they are or if you want to change.

**Comment by devcurmudgeon** [comment]
While we're on with this, there a preferred place for community realtime/chat discussion about doorstop? I noticed #doorstop on freenode is unused... am hanging out there...

**Comment by jacebrowning** [comment]
https://gitter.im/jacebrowning/doorstop is still the best place for discussion.

**Comment by jacebrowning** [comment]
At this point, I'd like to move forward with migrating this project to a GitHub organization as I no longer have the bandwidth to be the primary maintainer. If someone would like to create an organization (e.g. `doorstop-dev`), I will transfer the repository there.

cc @sebhub @stanislaw

**Comment by sebhub** [comment]
I will use Doorstop at least the next two years, but I cannot a make a commitment to maintain Doorstop. I am already quite busy as an [RTEMS](https://www.rtems.org) maintainer.

**Comment by stanislaw** [comment]
Similar on my end: I would not make a commitment to maintain Doorstop just yet, because the amount of how much I can contribute depends on whether my team can adopt it. In the worst case, I cannot promise a great oversight as a full-time maintainer.

At the same time, having a number of people in a separate organization should be fine.

**Comment by NouberNou** [comment]
I agree with @stanislaw. I'd argue transferring to an organization regardless of who is going to maintain it is valuable as, in my experience it tends to allow people to self-organize around a project.

I am currently working on something that has Doorstop at its core, so I am all for a more sustainable structure for maintaining it.

From my experience in aerospace the Doorstop has been looked at a few times now by some major organizations but while they love the idea (and getting out from under the thumb of some of the larger requirements tool vendors) it's just not there yet.

**Comment by NouberNou** [comment]
@jacebrowning I'd recommend you create an organization and bring in your collaborators as team members. If you decide to move away organizations support that somewhat naturally with multiple administrator positions.

**Comment by jacebrowning** [comment]
Done.

**Comment by larskurth** [comment]
It's at https://github.com/doorstop-dev/doorstop just for rerference
