### ISSUE TITLE
should we use [-p PARENT] or [-l LEVEL]

### ISSUE THREAD

**Issue by TingIsGitting** [doorstop-dev/doorstop#336]
Should we use

[-p PARENT] of doorstop create

or

[-l LEVEL] of doorstop add

to specify the hierarchy of requirements. Currently I use levels to specify the hierarchy of requirements, like:
![fnfcemdmamhjimbk](https://user-images.githubusercontent.com/51360969/58866430-e1170f00-86b8-11e9-9efe-728833715518.png)
But later on, we will have to write requirements of multiple hierarchies. We are not very clear about the correct use cases and the differences of the parent and level.

Thank you very much for your time.

**Comment by jacebrowning** [comment]
`doorstop create` results in a new document, while `doorstop add` results in a new item.

I think you want to use levels to specify the hierarchy.

**Comment by JustinW80** [comment]
@TingForGitHub , it depends on what you mean by "hierarchy of requirements".

In requirements management, you typically have a "document tree" with lower level documents linking up to higher level documents. (And sometimes bidirectional.) Document level meaning the level of detail, such as `enterprise <- system <- software`. So that's one type of hierarchy, the document tree. In Doorstop, you use `doorstop create --parent PARENT` to start a new child document in the tree and tell Doorstop to expect it to link to a parent document.

If you mean an outline level inside a document, that's where item's level number comes in and the use of `doorstop add --level LEVEL`. Generally, you want each leaf in the outline to be text and each parent node to be a heading. 

In your screenshot's use case, the subjects of your "shall"s are for three different system elements:

```
RTEMS
|
+-- IRQ Manager
  |
   +-- Interrupt Manger Extension API
```

To me, you would want three different documents for each of these elements and link to them.

That is, put all the "RTEMS shall" items in the root document. Then put all the the "The IRQ Manager shall" items in the a child document. And last put all the "The API shall"s in the grandchild document.
