### ISSUE TITLE
Optionally give a hint for the UID number selection

### ISSUE THREAD

**Issue by sebhub** [doorstop-dev/doorstop#349]
Doorstop selects the maximum UID number of all existing items of a document plus one for the UID number of a new item. A user may want to partition the number space so that the number can be used to indicate that an item belongs to a certain group, for example REQ0100..REQ0199 -> task requirements, REQ0200..REQ0299 -> semaphore requirements, REQ0300..REQ0399 -> message queue requirements. Sufficient gaps in the partitions allow a placement of future items into the right group. This feature could be realized with a new command line argument:

-n NUMBER, --number NUMBER

select the first available UID number greater than or equal to NUMBER for the new item

**Comment by jacebrowning** [comment]
I _think_ I support the addition of the feature, but I definitely want to avoid folks from imparting too much meaning into IDs to the point that they attempt to start deleting and reusing IDs.

What happens if a project already has REQ0100..REQ103 and someone needs to add a new requirement between REQ101 and REQ102?

Once the `--number` option has been used to create a requirement with a higher ID, how will someone insert a requirement with a much lower ID?

**Comment by joelsherrill** [comment]
This technique may not be common on small projects but it is used in larger projects and standards. For example, the ARINC 653 real-time operating system standard for avionics systems uses at least number ranges to group requirements. They reserved large blocks like 100 apart for API classes. This allows evolution over a long life project while grouping related requirements.

The alternative to this is a bunch of sequentially numbered requirements where numerical proximity bears no relationship to the logical grouping. 

This is just a technique where a project has something similar to a library shelves coding system based solely on numbers.

Another technique is to have a pattern like PROJNAME-SUBSYSTEM-NNNN. Personally I like this for grouping even more than just number ranges because it gives a logical name for humans to key off of. Having seen projects number test cases with no code to group them, I can attest that it is impossible to remember what test case 76 actually us unless it caused you great pain.

Grouping requirements logically by subsystem, API set, etc is important in a large project. If you managed requirements for the Python or C++ libraries, I suspect you would want to group them instead of a huge set of unrelated numbers. And language updates can be inserted or appended to the set. Which is easier to manage?

**Comment by sebhub** [comment]
In Doorstop the UID of an item is defined by its file name without the extension. An UID consists of two parts, the prefix and a number. The parts are divided by an optional separator. The prefix is determined by the document to which the item belongs. So, if you want a prefix for subsystems, then you have to create a document for each subsystem. I am not sure if this is the intended use case for documents.

**Comment by JustinW80** [comment]
I disagree that Doorstop's IDs should be used this way. They are a permalink to an item. Once an ID is set, you want to be able to refer to it from anywhere and not worry about it breaking.

Like @jacebrowning mentioned, if you need to add a new item within a blocked out ID range, it will get very messy.

> The alternative to this is a bunch of sequentially numbered requirements where numerical proximity bears no relationship to the logical grouping.

True, but numerical proximity does indicate a temporal relationship (numbers near each other were created closer in time).

Categorizing and grouping requirements can be handled using [custom extended attributes](https://doorstop.readthedocs.io/en/latest/reference/items/#extended-attributes), basically like tags.

You can change those attributes as you re-tag without affecting the permalink ID.

You could also link to a follow-on item's ID instead of trying to group their IDs together.

**Comment by michaelnt** [comment]
I can see the attraction of using number ranges, i.e. splitting a document into sections and having the numbers be similar for each range. I don't think having ranges means items will get renamed and visually it is nicer having the items near each other having similar IDs.

I noticed that the repo contains an item called [REQ2-001.yml](https://github.com/jacebrowning/doorstop/blob/develop/doorstop/core/tests/files/REQ2-001.yml) with a uid of REQ2-001 and trying that out it seems REQ1-001, REQADMIN-001 and REQ-ADMIN-001 all work. 

If you added a prefix option you still need to decide if the numbers are unique within just that prefix or across all the items of a document. I think it would be easy enough to find the highest numbered item with the specified prefix.

![image](https://user-images.githubusercontent.com/265155/61473526-76771580-a97e-11e9-9d2a-3c80e5addec3.png)

**Comment by sebhub** [comment]
I proposed to make this feature optional via a command line parameter. So, the default number allocation scheme will not change. Using number groups is obviously a best-effort approach. It is a user problem if its number group space is consumed. If you have a lot of references based on the UID in the code to satisfy the software component to requirement traceability the number grouping could be helpful, e.g. to grep in the code. Implementing this feature should be straight forward.

**Comment by sebhub** [comment]
I started to do some real work with Doorstop. I think that the number part of the UID is great as a default means without user input since it can be easily managed by the tool. However, doing a specification with several hundred items this way is not really nice. Especially when links have to be reviewed. We should generalize the number part of the UID and call it a `name`. The UID will consist of `document-prefix` + `separator` + `name`. For names it is required that the less then operator is defined to allow a sorting of UIDs. If a user does nothing, then the numbers will be generated as is. Optionally, a user should be able to specify a `name` through a command line parameter, e.g. `doorstop add -n NAME REQ`. In this case, we must check that the corresponding UID doesn't exist already. As a special case, this supports the number grouping of this issue.

**Comment by sebhub** [comment]
I opened pull request #428 to address this issue. Instead of the original proposal it adds a

```
$ doorstop add --help
[...]
  -n NAME, --name NAME        use the specified NAME instead of an
                              automatically generated number for the UID
                              (together with the document prefix and
                              separator); the NAME must not contain separator
                              characters or digits (default: None)
[...]
```

command line option to `doorstop add`. You can use it to specify a name for the new item. A name must not contain separator characters ('-', '_', and '.') or digits.  The name given at the command line may be a number, e.g. int(name) produces no Python exception. This can be used to work with number groups. Examples:

```
$ doorstop add -n TASKCREATE REQ
building tree...
added item: REQ-TASKCREATE (@/reqs/REQ-TASKCREATE.yml)
$ doorstop add -n TASKDELETE REQ
building tree...
added item: REQ-TASKDELETE (@/reqs/REQ-TASKDELETE.yml)
$ doorstop add -n 30 REQ
building tree...
added item: REQ-030 (@/reqs/REQ-030.yml)
$ doorstop add -n 40 REQ
building tree...
added item: REQ-040 (@/reqs/REQ-040.yml)
$ doorstop add REQ
building tree...
added item: REQ-041 (@/reqs/REQ-041.yml)
$ doorstop add -n 31 REQ
building tree...
added item: REQ-031 (@/reqs/REQ-031.yml)
$ doorstop add -n 31 REQ
building tree...
ERROR: item already exists: /src/doorstop/reqs/REQ-031.yml
$ doorstop publish REQ
building tree...
1.0     Overview
[...]
4.5     REQ015 Installation

        Doorstop **shall** provide a lightweight installation method.

        Child links: LLT007, LLT008

4.6     REQ-TASKCREATE

4.7     REQ-TASKDELETE

4.8     REQ-030

4.9     REQ-040

4.10    REQ-041

4.11    REQ-031
```

**Comment by c-mauderer** [comment]
I agree that there are use cases where this can improve the readability and therefore makes this more useful.

Note that there is a contradiction in the help text and the examples. The help text explicitly tells to not use digits but the examples contain numbers. So maybe the help text should be improved.
