### ISSUE TITLE
How well Doorstop can be integrated with Git

### ISSUE THREAD

**Issue by manojmsrit** [doorstop-dev/doorstop#414]
I am planning to link my git files using Doorstop. Can you please suggest regarding this and how this can be integrated with Gitlab. Please answer me and thank you for your help.

Regards,
Manoj

**Comment by JustinW80** [comment]
Hi @manojmsrit. Doorstop needs a version control system working underneath, and git is popular and supported. See the [usage guidance on Read The Docs](https://doorstop.readthedocs.io/en/latest/#usage).

Otherwise, your question is pretty broad. Are you asking for a suggested workflow to control your Doorstop artifacts in git?

**Comment by jacebrowning** [comment]
I believe this question has been answered. Please reopen if you need more information.
