### ISSUE TITLE
Allow multiple documents in the same folder

### ISSUE THREAD

**Issue by theovoss** [doorstop-dev/doorstop#42]
I tried creating two doorstop documents in the folder and got an error. I don't understand why this shouldn't be allowed.

**Comment by danlaudk** [comment]
Hi,  I have what I think is the inverse question ot this thread: Is there a way to (re-)use the **same item in multiple documents** (so that when I update the item, that change is reflected everywhere, without having to remember where else it lives). The issue  with links (i think) is with readability. And document isolation (I may not want readers looking at other documents, even though limiting readership doesn't need to be securely so, but a nice to have). btw,  this looks a great tool!

**Comment by jacebrowning** [comment]
@danlaudk An item can only be part of one document. The best option for isolation would be to create a 3rd "shared" document that contains items required by two or more documents.

**Comment by danlaudk** [comment]
That sounds promising. How would I get the two or more documents to include
a shared item  (not merely as links)? (ie. what's the series of commands?)

**Comment by jacebrowning** [comment]
Unfortunately, this approach would still use links. Are you finding that navigating between the links takes too long?

**Comment by danlaudk** [comment]
my readers need to see it in a format that they are used to: all relevant
info on one doc. it's also a pilot, so what i produce needs to be capable
of current output in order to motivate a shift.

**Comment by jacebrowning** [comment]
Understood. I'll think about this some more. If you submit a new issue with a rough idea of how this feature might work, I'll add it to the backlog.
