### ISSUE TITLE
Add templating to publishing functionality

### ISSUE THREAD

**Issue by wojciechczerniak** [doorstop-dev/doorstop#515]
Hello,

This time a feature request. 

## Problem

I've seen that there are few requests/issues with customization of the Markdown output:

- [x] #166
- [x] #295
- [x] #469
- [ ] #513 
- [x] #314

And I would have few others requirements:

- Start from 2nd lvl header
- Format links as list
- Add custom class to up/down links
- Insert table of contents 
- Various smaller formatting adjustments

But IMO a change from string building to one of the templating languages may solve all of the above in a one go

## Solution idea

I think Jinja2 is the number one for Python libraries? With a template and an ability to use our own fixing all of the above issues would be just a matter of customization with `--template my-markdown.jinja2`

Remove hard-coded string building in HTML publisher:
https://github.com/doorstop-dev/doorstop/blob/a770dc4566a43de87da0e5be61dfedf87a7ac57d/doorstop/core/publisher.py#L165-L167
and Markdown markdown publisher:
https://github.com/doorstop-dev/doorstop/blob/a770dc4566a43de87da0e5be61dfedf87a7ac57d/doorstop/core/publisher.py#L399-L409

With Jinja2 templates defaulting to whatever is in those methods:

```jinja
# {{ document.header }}

{% for item in document.items %}
  ## {{ item.header }} <small>{{ item.id }}</small> { #{{ item.id }} }
  
  {{ item.text }}
  
  {% if item.PUBLISH_CHILD_LINKS %}  
  Links:
    {% for link in links %}
        [{{ link.header }}]({{ link.file }}#{{ link.id }})
    {% endfor %}
  {% endif %}
  
  {% if item.document.publish %}  
        | Attribute | Value |
        | --------- | ----- |
    {% for attr in item.document.publish %}
        | {{ attr }} | {{ item.attribute(attr) }} |
    {% endfor %}
  {% endif %}
{% endfor %}
```

AND allow the `--template` arg for all output formats.

```sh
doorstop publish -m all docs/requirements/ --template my-template.jinja2
```

## Use cases

You want Frontmatter/YAML headers in Markdown #295, just add them to the template:

```jinja
---
title: {{ page.header | title() }}
metadata: {{ page.description | truncate(240) }}
---
{% block content %}
.... content
```

Footer maybe as in #166? Add it at the end:

```jinja
.... content
{% endblock  %}

Copyright Year, Restrictions
```

**Comment by eterX** [comment]
Hi Wojciech

I realize that it would be a *very useful* feature. I've been using something like that, for communication documents (but without Jinja, your approach looks far more sound)

As soon as a I get #507 done, count on some help on this :)

Leandro

**Comment by eterX** [comment]
Hi!

As promissed, started exploring this feature along with @lucasd92, now that #507 is finally waiting to be merged, (maybe @jacebrowning ?) :)
@lucasd92 managed to replace Bottle's default template engine with Jinja2. Please, see [this fork (branch feature/jinja)](https://github.com/eterX/doorstop/tree/feature/jinja) that can give us a glipse of the feature's potential, by:

- issuing the command `doorstop publish all /mydir -H --template test_jinja2` 
- tweaking `views/test_jinja2_index.tpl`
- modifying the test at `test_all.py`

Looks promissing! 

First pitfall we came across: Jinja2's output can be consumed as an  iterator, and Doorstop expects that. Thusly allowing for [iterator chains](https://github.com/eterX/doorstop/blob/e7184623fcc8469fee165ca6d902c3db52268280/doorstop/core/publisher.py#L233) and coroutines. But it looks like iterators composition is lost in Bottle.Jinja2Template. In spite of the description saying  "Get a rendered template as a string iterator" it calls render() instead of generate() with no altarnetive. Workarounded [here](https://github.com/eterX/doorstop/blob/e7184623fcc8469fee165ca6d902c3db52268280/doorstop/core/publisher.py#L158), somewhat piercing Bottle's abraction.
IMHO, it might not be an important difference in terms for small/big projects, but for future API endpoints. Maybe more if the  project moves to FastAPI and async methods?



Best regards,

**Comment by yoyodyn** [comment]
Would it be possible to specify the publishing template within the .doorstop.yml file for each document/type?

**Comment by neerdoc** [comment]
@wojciechczerniak Could you have a look at version v.3.0b12 and see if you think this version solves this issue?
