### ISSUE TITLE
Add release tags to Beta

### ISSUE THREAD

**Issue by villanella** [doorstop-dev/doorstop#613]
There are no release tags for Doorstop Beta.
It's difficult to go to the commit corresponding the most stable beta version 3.0b4.

Please, add tags for beta.

**Comment by neerdoc** [comment]
@jacebrowning What is your opinion on this? I have no issue with adding beta tags.

**Comment by jacebrowning** [comment]
@neerdoc I have no objection to someone adding them. I haven't typically done that because prerelease tags aren't necessarily in chronological order nor is there any guarantee of consistent functionality between adjacent numbers.

I wasn't originally intending for the 3.0 beta to be out this long, but there's still work to close out the milestone: https://github.com/doorstop-dev/doorstop/milestone/16

**Comment by neerdoc** [comment]
So how do I do this? I suppose it is automated in some way how this is done? And are we talking here on github only or are we also talking about pypi?

**Comment by neerdoc** [comment]
I tried adding the two latest PRs as pre-releases. They are in _draft_ for now. Can you check them if that's how it should be done? @jacebrowning

**Comment by neerdoc** [comment]
Beta tags added.
