### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by hruhland-mtm** [doorstop-dev/doorstop#684]
Doorstop v2.2.1 is not compatible with python versions later than 3.12 (default on ubuntu 24.04 LTS) due to depreciation of pkg_resources as mentioned by this issue: https://github.com/mu-editor/mu/issues/2485

This appears to have already been fixed in the dev branch earlier this year: https://github.com/doorstop-dev/doorstop/commit/7ab309cb489b11679a2c1564d0ec824331e0bef6

I resolved my issue by downgrading python to an earlier version.

**Comment by MarkoSchuetz** [comment]
I just ran into this, since I'm not very familiar with Python and tooling, I'll share what I did to help those in a similar position. I installed `pyenv`. Then ran
```
pyenv install 3.12.8
```
which created a local installation of Python in `~/.pyenv`. With
```
pyenv shell 3.12.8
```
I set Python for this shell to the earlier version. I still had to include the`--python python3.12` switch on the `pipx` command-line:
```
pipx reinstall --python python3.12 doorstop
```
